-- OPC 军师数据库初始化（MySQL 8+）
-- 请先创建数据库，并在该数据库中执行本文件。

CREATE TABLE IF NOT EXISTS users (
  uuid CHAR(36) PRIMARY KEY,
  email VARCHAR(254) NOT NULL UNIQUE,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  last_login_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS email_login_codes (
  email VARCHAR(254) PRIMARY KEY,
  code_hash VARCHAR(64) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  sent_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
